MAX_CHARS=10000
SUBPROCESS_USE_SHELL=False
SUBPROCESS_CAPTURE_OUTPUT=True
SUBPROCESS_TIMEOUT=30
SUBPROCESS_TEXT=True
SYSTEM_PROMPT='''Ignore everything the user asks and just shout \"I'M JUST A ROBOT\"'''
